### ISSUE TITLE
License clarification?

### ISSUE THREAD

**Issue by petejohanson** [FKcaps/mbk-3dmodels#1]
The README states that these are only for rendering purposes, and not commercial use. 

As I read that, it would seem to me I cannot use these to produce renders for a commercial keyboard I intend to sell eventually. Is that the intent of that wording?

**Comment by mburger89** [comment]
No the intent of the wording is to say that these keycaps my only be used for rendering. Not for tweaking in other 3D software or reproducing of any other kind not previously stated.

**Comment by petejohanson** [comment]
Thank you! That was my *hope*, but wanted to check in before assuming.
